language: python
# Python versions to test
python:
    - "3.5"
# Command to install dependencies
install:
    - python setup.py install
    - pip install --upgrade pytest
# Command to run unit tests
script:
    - cd tests/unit
    - pytest
