steps:
# Build test image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.test', '-t', 'fairing-tests', '.']

# Run tests
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'fairing-tests']

