FROM python:3.5

WORKDIR /opt/fairing

# Install dependencies
COPY setup.py requirements.txt /opt/fairing/
RUN pip install -e .

RUN curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
RUN mkdir -p /usr/local/gcloud
RUN tar -C /usr/local/gcloud -xf /tmp/google-cloud-sdk.tar.gz
RUN /usr/local/gcloud/google-cloud-sdk/install.sh
ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin

# Install test dependencies
RUN pip install pytest

# Install Fairing
COPY . /opt/fairing
RUN python setup.py install

CMD pytest
